version: "3.1"

services:
    database:
        container_name: edutrack-db
        image: pgvector/pgvector:pg14
        env_file:
            - .env
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
            - "5432:5432"
        volumes:
            - ./.postgres-data:/var/lib/postgresql/data
