"""add question marks

Revision ID: 175f8976a60e
Revises: 959aa9b23a5d
Create Date: 2025-02-21 13:46:41.169759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175f8976a60e'
down_revision: Union[str, None] = '959aa9b23a5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('marks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'marks')
    # ### end Alembic commands ###
