"""remove unnecessary optional fields for db

Revision ID: 4261a9480485
Revises: 53c4a7da68ff
Create Date: 2025-03-21 20:56:56.090182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4261a9480485'
down_revision: Union[str, None] = '53c4a7da68ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'question_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'mark',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'mark',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('questions', 'question_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
