"""add mark column to questions table

Revision ID: 53c4a7da68ff
Revises: 91c82fc3d294
Create Date: 2025-03-11 14:16:58.437745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53c4a7da68ff'
down_revision: Union[str, None] = '91c82fc3d294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('mark', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'mark')
    # ### end Alembic commands ###
