"""Add student_scores column to papers table

Revision ID: 959aa9b23a5d
Revises: e56ba794547a
Create Date: 2025-01-28 15:36:51.656569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959aa9b23a5d'
down_revision: Union[str, None] = 'e56ba794547a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('student_scores', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'student_scores')
    # ### end Alembic commands ###
