"""Add courses

Revision ID: ae73225071cc
Revises: 0a3b3d3aa847
Create Date: 2025-03-31 18:49:27.321021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae73225071cc'
down_revision: Union[str, None] = '0a3b3d3aa847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('papers', sa.Column('course_id', sa.Integer(), nullable=False))
    op.add_column('papers', sa.Column('student_scores', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'papers', 'courses', ['course_id'], ['id'])
    op.drop_index('questions_embedding_idx', table_name='questions', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('questions_embedding_idx', 'questions', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_column('papers', 'student_scores')
    op.drop_column('papers', 'course_id')
    op.drop_table('courses')
    # ### end Alembic commands ###
