"""Add courses

Revision ID: e56ba794547a
Revises: 91c82fc3d294
Create Date: 2025-01-28 12:24:30.147397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e56ba794547a'
down_revision: Union[str, None] = '91c82fc3d294'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('papers', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'papers', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_column('papers', 'course_id')
    op.drop_table('courses')
    # ### end Alembic commands ###
